### ISSUE TITLE
dataset.sh does not create the normalized.bin files

### ISSUE THREAD

**Issue by ghost** [amaneureka/Stylus#2]

**Comment by amaneureka** [comment]
Yes. dataset.sh only download dataset from the server. you have to execute ```python normalize.py``` to get binary files.

> You can preprocess data after downloading dataset by executing python normalize.py
> It expects that system has all the dependencies installed
> - pip3 install -r requirements.txt
> - bash ./dataset.sh
> It will create two files normalized-train.bin & normalized-val.bin under dataset directory.

**Comment by ghost** [comment]
Oh thank you for pointing that out. May I suggest adding `python normalize.py` as a step after `bash ./dataset.sh` to make it more clear?
